name: Lint
# Lint runs golangci-lint over the entire cosmos-sdk repository
# This workflow is run on every pull request and push to master
# The `golangci` will pass without running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
  push:
    branches:
      - develop
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@master
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
